name: walking_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.3.2
  flutter_riverpod: ^2.3.6
  flex_color_scheme: ^7.0.0
  health: ^7.0.0
  permission_handler: ^10.2.0
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
